import type { 
  Task, TimeBlock, User, Goal, CalendarEvent, 
  Milestone, DailyReview, AvailabilityTemplate, BreakPolicy 
} from '../types';

const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);

export const seedData = {
  user: {
    id: 1,
    email: 'user@tamitilanes.com',
    first_name: 'Alex',
    last_name: 'Chen',
    timezone: 'Africa/Kampala',
    coach_settings: {
      mode: 'copilot' as const,
      allow_cross_boundary_flex: true,
      weekly_quotas: [],
    },
  } as User,

  tasks: [
    {
      id: 1,
      project: 1,
      domain: 'professional' as const,
      context: 'dev',
      title: 'Implement user authentication',
      notes: 'OAuth integration with Google and GitHub',
      estimate_min: 120,
      allow_split: true,
      difficulty: 4,
      importance: 5,
      due_at: tomorrow.toISOString(),
      readiness: 0.8,
      energy_tag: 'high' as const,
      status: 'backlog' as const,
      dependencies: [],
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      project: null,
      domain: 'personal' as const,
      context: 'exercise',
      title: 'Morning workout',
      notes: '30 minutes strength training',
      estimate_min: 30,
      allow_split: false,
      difficulty: 2,
      importance: 4,
      due_at: null,
      readiness: 1.0,
      energy_tag: 'high' as const,
      status: 'backlog' as const,
      dependencies: [],
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 3,
      project: 1,
      domain: 'professional' as const,
      context: 'writing',
      title: 'Write API documentation',
      notes: 'Document all endpoints with examples',
      estimate_min: 90,
      allow_split: true,
      difficulty: 3,
      importance: 3,
      due_at: null,
      readiness: 0.6,
      energy_tag: 'med' as const,
      status: 'backlog' as const,
      dependencies: [1],
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 4,
      project: null,
      domain: 'personal' as const,
      context: 'reading',
      title: 'Read "Atomic Habits" chapter 3',
      notes: 'Take notes on habit stacking',
      estimate_min: 25,
      allow_split: false,
      difficulty: 1,
      importance: 2,
      due_at: null,
      readiness: 1.0,
      energy_tag: 'low' as const,
      status: 'backlog' as const,
      dependencies: [],
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 5,
      project: 2,
      domain: 'professional' as const,
      context: 'calls',
      title: 'Client check-in call',
      notes: 'Weekly sync with Project Moonlight client',
      estimate_min: 60,
      allow_split: false,
      difficulty: 2,
      importance: 4,
      due_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      readiness: 0.9,
      energy_tag: 'med' as const,
      status: 'backlog' as const,
      dependencies: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Task[],

  timeBlocks: [
    {
      id: 1,
      task: 2,
      starts_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 7, 0).toISOString(),
      ends_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 7, 30).toISOString(),
      status: 'committed' as const,
      source: 'manual' as const,
      domain: 'personal' as const,
      title: 'Morning workout',
      context: 'exercise',
    },
    {
      id: 2,
      task: 1,
      starts_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 0).toISOString(),
      ends_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 0).toISOString(),
      status: 'committed' as const,
      source: 'scheduler' as const,
      domain: 'professional' as const,
      title: 'Implement user authentication',
      context: 'dev',
    },
    {
      id: 3,
      task: 4,
      starts_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 20, 0).toISOString(),
      ends_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 20, 25).toISOString(),
      status: 'draft' as const,
      source: 'scheduler' as const,
      domain: 'personal' as const,
      title: 'Read "Atomic Habits" chapter 3',
      context: 'reading',
    },
  ] as TimeBlock[],

  goals: [
    {
      id: 1,
      domain: 'personal' as const,
      context: 'exercise',
      target: { unit: 'min/week', value: 150 },
      period: 'week',
      streak: 3,
      current_progress: 90,
    },
    {
      id: 2,
      domain: 'personal' as const,
      context: 'reading',
      target: { unit: 'min/day', value: 30 },
      period: 'week',
      streak: 12,
      current_progress: 25,
    },
    {
      id: 3,
      domain: 'professional' as const,
      context: 'deep-work',
      target: { unit: 'min/day', value: 120 },
      period: 'week',
      streak: 5,
      current_progress: 240,
    },
  ] as Goal[],

  events: [
    {
      id: 1,
      domain: 'professional' as const,
      title: 'Team standup',
      starts_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 0).toISOString(),
      ends_at: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 30).toISOString(),
      all_day: false,
      location: 'Conference Room A',
      context: 'meeting',
    },
    {
      id: 2,
      domain: 'personal' as const,
      title: 'Dentist appointment',
      starts_at: new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate(), 14, 0).toISOString(),
      ends_at: new Date(tomorrow.getFullYear(), tomorrow.getMonth(), tomorrow.getDate(), 15, 0).toISOString(),
      all_day: false,
      location: 'Downtown Dental',
      context: 'health',
    },
  ] as CalendarEvent[],

  milestones: [
    {
      id: 1,
      domain: 'professional' as const,
      project: 1,
      title: 'MVP Launch',
      due_at: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      importance: 5,
      notes: 'Launch minimum viable product to beta users',
    },
    {
      id: 2,
      domain: 'personal' as const,
      project: null,
      title: 'Complete "Atomic Habits"',
      due_at: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
      importance: 3,
      notes: 'Finish reading and implement 3 new habits',
    },
  ] as Milestone[],

  dailyReviews: [
    {
      id: 1,
      date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      planned_min: 480,
      actual_min: 420,
      completed_tasks: 4,
      missed_blocks: 1,
      interruptions: 3,
      mood: 4,
      top_win: 'Completed authentication system ahead of schedule',
      main_blocker: 'Too many interruptions during deep work',
      notes: 'Good day overall, need to protect focus time better',
      balance_score: 0.1,
    },
  ] as DailyReview[],

  availabilityTemplates: [
    {
      id: 1,
      weekday: 1, // Monday
      start_time: '08:00',
      end_time: '20:00',
      energy_curve: {
        '08:00': 'high',
        '10:00': 'high',
        '12:00': 'med',
        '14:00': 'low',
        '16:00': 'med',
        '18:00': 'low',
      },
      personal_windows: [
        { start: '06:30', end: '08:30' },
        { start: '19:00', end: '21:00' }
      ],
      professional_windows: [
        { start: '09:00', end: '18:00' }
      ],
    },
  ] as AvailabilityTemplate[],

  breakPolicies: [
    {
      id: 1,
      work_min: 25,
      short_break_min: 5,
      long_break_every: 4,
      long_break_min: 15,
    },
  ] as BreakPolicy[],
};